name: App Build

on:
  push:
    branches: [ "master" ]

env:
  AppVersion: '0.1.${{ github.run_number }}.0'

jobs:
  build:
    strategy:
      matrix:
        configuration: [ Release ]
        platform: [ x64, x86 ]
    runs-on: windows-latest
    env:
      Platform: ${{ matrix.platform }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Publish
        run: |
          dotnet publish `
          -c Release `
          -o "${{ github.workspace }}\app\release\${{ env.Platform }}" `
          -r win-${{ env.Platform }} `
          -p:PlatformTarget=${{ env.Platform }} `
          -p:Version="${{ env.AppVersion }}" `
          -p:FileVersion="${{ env.AppVersion }}" `
          -p:AssemblyVersion="${{ env.AppVersion }}"

      - name: Upload binary artifacts
        uses: actions/upload-artifact@v3
        with:
          name: touch${{ env.Platform }}
          path: ${{ github.workspace }}\app\release\${{ env.Platform }}\touch-${{ env.Platform }}.exe

  purge:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 1